### ISSUE TITLE
update MCF-SSP dependency

### ISSUE THREAD

**Issue by koebi** [LPMP/LPMP#1]
In the latest commit in MCF-SSP, functions are added that are used in this code.
However, the code still depends on the second-to-last commit.

An example of this is [mcf_->reset_costs()](https://github.com/LPMP/LPMP/blob/c7586822aa26737bc9ef056a860c8a44a974c161/include/graph_matching/graph_matching_constructor.hxx#L419)

**Comment by pawelswoboda** [comment]
Done. Possibly there are some other issues as well, I am currently checking.

**Comment by koebi** [comment]
Thanks a lot for fixing this :)
