### ISSUE TITLE
Error when "make"

### ISSUE THREAD

**Issue by UsedToBe97** [LPMP/LPMP#13]
Hi,

When I use `make` after `cmake .`
I got the following errors:
![image](https://user-images.githubusercontent.com/33629224/79048708-8b54b100-7c51-11ea-9c48-fbf5220cf44c.png)

Could anybody tell me what to do?

**Comment by pawelswoboda** [comment]
Could you tell me which compiler and which distribution you use?

**Comment by UsedToBe97** [comment]
It's gcc 8.1.0 and ubuntu 18.04. 




            
            
                
                    
                            
                                
                            
                            
                                usedtobe
                            
                            
                                
                            
                    
                        
                            
                                    邮箱：usedtobe@sjtu.edu.cn
                            
                        
                
            
        Signature is customized by Netease Mail Master


On 04/12/2020 02:21, Paul Swoboda wrote: 
Could you tell me which compiler and which distribution you use?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/LPMP/LPMP/issues/13#issuecomment-612482538",
"url": "https://github.com/LPMP/LPMP/issues/13#issuecomment-612482538",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by UsedToBe97** [comment]
> Could you tell me which compiler and which distribution you use?

It's gcc 8.1.0 and ubuntu 18.04
