### ISSUE TITLE
Error when installing lpmp

### ISSUE THREAD

**Issue by YuYanXiaoJi** [LPMP/LPMP#21]
Hi  ,  ;-)
when i run "python3 -m pip install git+https://github.com/lpmp/LPMP.git", i got a error as follows.
Here is my envs:

`
Ubuntu 5.4.0-6ubuntu1~16.04.9
gcc versioon: 9.3.0
cmake version: 3.19.0-rc2
`

How could i fix this error?
Many thanks ! 

![image](https://user-images.githubusercontent.com/23171037/97801525-55702c00-1c78-11eb-8e45-7573a23b0307.png)

![image](https://user-images.githubusercontent.com/23171037/97801512-45584c80-1c78-11eb-8bb0-bb94d999808d.png)

**Comment by fukexue** [comment]
I'm sorry to disturb you. Have you solved the problem? I have the same problem.

**Comment by fukexue** [comment]
> Hi , ;-)
> when i run "python3 -m pip install git+https://github.com/lpmp/LPMP.git", i got a error as follows.
> Here is my envs:
> 
> `Ubuntu 5.4.0-6ubuntu1~16.04.9 gcc versioon: 9.3.0 cmake version: 3.19.0-rc2`
> 
> How could i fix this error?
> Many thanks !
> 
> ![image](https://user-images.githubusercontent.com/23171037/97801525-55702c00-1c78-11eb-8e45-7573a23b0307.png)
> 
> ![image](https://user-images.githubusercontent.com/23171037/97801512-45584c80-1c78-11eb-8bb0-bb94d999808d.png)

I'm sorry to disturb you. Have you solved the problem? I have the same problem.
