### ISSUE TITLE
Invalid identifiers in python code

### ISSUE THREAD

**Issue by koebi** [LPMP/LPMP#3]
The identifier '3_instance_list' in https://github.com/LPMP/LPMP/blob/9259497f35b8059b5c29fef9b9acec0d20fd7d36/src/graph_matching/eval/worms_mm_evaluation_data.py.in#L5 is invalid - as are all the others beginning with numbers.

**Comment by koebi** [comment]
if they should only be renamed I am more than happy to provide a patch :))

**Comment by pawelswoboda** [comment]
I have renamed them.
